(() => {
  "use strict";

  const SED = window.SED;

  SED.Constants = {
    DEFAULT_SCENE_TIMEOUT: 3600,
    MAX_CHOICE_OPTIONS: 6,
    DEFAULT_QTE_WINDOW: 60,
    DEFAULT_QTE_TIME_LIMIT: 180,
    DEFAULT_QTE_MASH_TARGET: 10,
    DIALOGUE_LOG_MAX_ENTRIES: 100,
    NVL_MAX_BACKLOG: 200,
    TOAST_FADE_STEP: 15,
    TOAST_DEFAULT_DURATION: 180,
    GRAIN_BITMAP_SIZE: 256,
    GRAIN_DENSITY: 0.4,
    BUST_ENTER_DURATION: 20,
    BUST_EXIT_DURATION: 20,
    UNFOCUSED_OPACITY: 128,
    LOOP_MAX_ITERATIONS: 10000,
    DEFAULT_EFFECT_DURATION: 30,
  };

  SED.registerModule("Constants", "1.0.0");
})();
